version: "3"
services:
    flaskapp:
        build: .
        depends_on:
            - db
        ports:
            - 5000:5000
    db:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=mysecretpw
            - POSTGRES_USER=myuser
            - POSTGRES_DB=mydb
    adminer:
        image: "adminer"
        ports:
            - 8080:8080
